### ISSUE TITLE
ruby [info]

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [PentestBox/tracker#97]
Hello, 

i tested most latest ruby versions 
and i can inform you that the latest one which work fine with metasploit , wpscan .... is : [ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.2.4-i386-mingw32.7z)

good luck

**Comment by BilikoX** [comment]
real good job
